feat(resize): add native resize capabilities to editor
Teradata/covalent-code-editor pull request #65
Opened 2019-04-08 19:00 UTC by emoralesb05

instead of using automaticLayout + layout fixes

This to improve performance and allow proper e2e testing since the intervals would get in the way.

Also removed unwanted scrollbars and resize in a single step instead of adjustments every 200ms.

2019-04-18 19:59 UTC, christianmemije requested changes
Let's not pass in automaticLayout to the monaco editor and just use this implementation instead.

2019-04-22 17:44 UTC, christianmemije approved these changes
LGTM

2019-05-08 03:56 UTC, emoralesb05 commented on src/platform/code-editor/code-editor.component.scss
> +  overflow: hidden;
Reminder to remove this.

2019-05-08 03:57 UTC, emoralesb05 commented on src/platform/code-editor/code-editor.component.ts
> +  @Input('automaticLayout') automaticLayout: boolean = true;
Reminder to add a console.warn for deprecation

2019-06-08 03:40 UTC, merged